### ISSUE TITLE
graphics/icons/binding-chitin.png is not a PNG file

### ISSUE THREAD

**Issue by baracoder** [Dysoch/DyWorld#19]
For me Factorio (0.15.39, Linux) won't start properly with DyWorld 0.5.0 enabled, it is unable to open graphics/icons/binding-chitin.png
I have extracted it and it turns out to be a jpeg. After updating the archive with a png it works.

**Comment by Dysoch** [comment]
Linux is weird sometimes. The file is a png at my dev side and it clearly is in the zip file. Weird.

Should this happen again, let me know. Might be a Linux fault

**Comment by baracoder** [comment]
Thank you for the reply.
Yea this is wired, i have just downloaded the 0.5.1 version from the mod portal and unzipped it:
```
bara@reason ~/Downloads % file DyWorld_0.5.1/graphics/icons/binding-copper.png
DyWorld_0.5.1/graphics/icons/binding-copper.png: PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
bara@reason ~/Downloads % file DyWorld_0.5.1/graphics/icons/binding-chitin.png
DyWorld_0.5.1/graphics/icons/binding-chitin.png: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, progressive, precision 8, 32x32, frames 3
```
Also the background on this ion is white for me, not transparent like the others.
Maybe the library used on Linux for loading the images is more strict then the one used on Windows. Can you please check again?
