### ISSUE TITLE
LuaItemStack not valid for read

### ISSUE THREAD

**Issue by BlackCapCoder** [Dysoch/DyWorld#273]
I have a personal convenience mod which among other things let me press a key to craft more of my cursor item. Doing this while holding a ghost item consistently causes DyWorld to crash on this line:
https://github.com/Dysoch/DyWorld/blob/c55a27ff8a8b510937ab867e23cc2562af3152fb/DyWorld/control.lua#L112

I fixed this locally by preprending the line with:
```lua
if not event.item_stack.valid_for_read then return end
```

I think this is the relevant part of my own mod that causes DyWorld to crash, but I have not tested this
```lua
-- If cursor was a ghost, swap to the crafted item
script.on_event(defines.events.on_player_crafted_item, function (ev)
  local gh = player.cursor_ghost

  if gh == nil or gh.name ~= ev.item_stack.name then return end

  player.cursor_stack.swap_stack (ev.item_stack) --   <-- HERE
end)
```

Either way, it doesn't hurt to throw in an extra check?

**Comment by Dysoch** [comment]
Could you provide the mod so i can test it once i fix it?

**Comment by BlackCapCoder** [comment]
The full thing is a maze of dead code that I'd rather not share, but here's the relevant parts

```lua
---------- Global player object

pl = nil

script.on_nth_tick (1, function (ev)
  pl = game.players[1]
  script.on_nth_tick (1, nil)
end)


---------- Get/Set cursor

function getCursor ()
  local cursor = pl.cursor_stack

  if not cursor.valid_for_read or cursor == nil then
    cursor = pl.cursor_ghost
  end

  if cursor == nil then
    return nil
  else
    return cursor.name
  end
end

function setCursor (item)
  if item == nil then
    pl.clean_cursor ()
    return
  end

  local stack = pl.get_main_inventory().find_item_stack(item)

  if stack ~= nil then
    pl.cursor_stack.swap_stack (stack)
  else
    pl.cursor_ghost = item
  end
end


---------- Craft more of cursor object

function craftCursor (count)
  local cur = getCursor ()
  if cur == nil then return end

  local r = pl.force.recipes[cur]
  if r == nil then return end

  pl.begin_crafting({count = count, recipe = r, silent = false})
end

-- If cursor was a ghost, swap to the crafted item
script.on_event(defines.events.on_player_crafted_item, function (ev)
  local gh = pl.cursor_ghost

  if gh == nil or gh.name ~= ev.item_stack.name then return end

  pl.cursor_stack.swap_stack (ev.item_stack)
end)


------------- Key hooks

-- Copy selected entity to cursor
script.on_event("yank-selected", function (ev)
  local sel = pl.selected
  if sel == nil then return end
  local r = pl.force.recipes[sel.name]
  if r == nil then return end
  setCursor (r.name)
end)


script.on_event("craft-cursor", function (ev)
  craftCursor (1)
end)

script.on_event("craft-cursor-five", function (ev)
  craftCursor (5)
end)
```

Steps to repro:
* Create a new world with default settings
* Chop enough wood for at least 2 crates
* Craft exactly 1 crate and place it in the world
* While hovering over the create, invoke "yank-selected"
* Invoke "craft-cursor"

The game will crash as soon as the second crate is crafted

**Comment by Dysoch** [comment]
This seems like a nice QoL improvement as well, would you be up for allowing me to add it into DyWorld, with all credits given towards you?

Either way, will have it fixed before next release, implementation if you agree with it will be later versions

**Comment by Dysoch** [comment]
Fixed for next version

**Comment by BlackCapCoder** [comment]
> would you be up for allowing me to add it into DyWorld, with all credits given towards you?

Absolutely! Although QoL features might be out of scope for DyWorld?

I actually have quite a few of these QoL features- some more controversial than others. If you have a channel I can contact you on and the ability to mentor me, I've been meaning to extract the more generally useful bits and publish my first mod.

**Comment by Dysoch** [comment]
You can find me on Discord: https://discord.gg/yR5vBWy
