### ISSUE TITLE
Graphic bug (belt is not colored correctly enymore)

### ISSUE THREAD

**Issue by Trdonja00** [Dysoch/DyWorld#283]
From the new update my tier 1&2 belt is not colored correctly enymore. When I place it on the ground both tiers get colored as a vanila tier 1 belt. I can't test other tiers (not there yet). It is the same when I use only this mod. 
![Belt graphic bug](https://user-images.githubusercontent.com/55735071/65491307-138a8900-deaf-11e9-9588-57df9eb6787c.png)

**Comment by DoomDutch** [comment]
Known bug. Should be fixed this Thursday, I heard.
