### ISSUE TITLE
Upgrade planner works funky when skipping a tier

### ISSUE THREAD

**Issue by Dysoch** [Dysoch/DyWorld#285]

**Comment by Dysoch** [comment]
cant find the issue, seems to be working properly. Closing for now. Anymore has more problems, let me know!

**Comment by NoLongerBreathedIn** [comment]
KatherineOfSky is doing a DyWorld series. In Episode 20 (youtu.be/QuCpedW_VU4), she tried to use the upgrade planner to turn regular inserters into heated inserters. They turned into fast inserters. Something's clearly wrong here.
