### ISSUE TITLE
Sandbox Mode Broken

### ISSUE THREAD

**Issue by macdjord** [Dysoch/DyWorld#292]
DyWorld handled sandbox mode poorly:

* The 'enable all research' cheat doesn't research all the DyWorld techs, and those it misses vaish from the research screen. Also, some vanilla techs that are not in DyWorld get researched anyway.
* The research queue doesn't work
* There are no recipes for spawning ores into your inventory in god-mode.
* The starter pack contains vanilla items that are otherwise disabled.

**Comment by Dysoch** [comment]
working on the starting items.
but after some testing, all techs are researched though, as it should. The command that triggers it research ALL tech from the player force, except infinite. And since DyWorld 0.8.6 doesnt remove a single tech, all vanilla techs get researched. So if you can clarify which techs vanish, i can look into it

how doest the research queue work? in sandbox mode its the default that after a rocket is launched, its enabled, which works on my end.

spawning resources recipes have never been in the god mode, and wont add that

**Comment by macdjord** [comment]
# Vanilla Research
Using the 'All research' cheat, I have the following tech researched:
  * Name: 'Nuclear power'
  * Price: (1 Red, 1 Green, 1 Blue, 30s) * 800
  * Dependencies: Uranium Processing
  * Effects: Heat Exchanger, Heat Pipe
I'm pretty sure that's not supposed to me there.

# Missing Research (Actually Search Bug)
I was wrong about this, but my error was the result of another bug: If, after using the 'All research' cheat, I open the tech window and search for 'heat', only two techs show up: the above-mentioned 'Nuclear Power', and DyWorld's 'Heat Management & Nuclear Energy 10'. None of the other DyWorld nuclear techs show up in the result, nor do they show up as not-yet-researched if I clear the search field, thus my original belief that they were skipped & locked out.

In truth, the other techs *have* been researched, and I can find them in the prereq tree of Nuke 10. It's just the search results that are wrong.

# Tech Queue
My mistake. Disregard that.

# Spawn Ores
My mistake. Disregard that. (I thought I remembered there being recipes in vanilla to create stacks of ore in your inventory. It seems like an obvious thing to want for testing designs)

**Comment by Dysoch** [comment]
vanilla research wasnt removed yet in the latest release, but is now in the next update. 
With the search bug its actually quite simple (quote from me to KatherineOfSky:)

> The thing about the tech tree and farming 3 “not showing”. In dyworld, all tech is, if applicable, an upgrade from its previous research. This means that in the left side it will only show the tech you can research, not the one after that. To find the one it will unlock it can be seen in the right side of the tech tree. This has been done to make sure the tech tree is not a huge mess, since more then 150 techs were added
> Once you researched farming 2, farming 3 will show up on the left
