### ISSUE TITLE
Loader Graphics

### ISSUE THREAD

**Issue by DaveSharman** [Dysoch/DyWorld#294]
Hi, this is an interesting mod,. most fun.

Ok, way back in 0.7 somewhere the change logs make reference to loader graphics with Deadlock's graphics.   I'm seeing just the generic loader graphics.    Any particular one of Deadlocks's mods needed for this?

thanks,

d.

factorio: 0.17.69.
mods: all at latest version

{
  "mods": [
    {
      "name": "base",
      "enabled": "true"
    },
    {
      "name": "actual-craft-times-remade",
      "enabled": "true"
    },
    {
      "name": "AfraidOfTheDark",
      "enabled": "true"
    },
    {
      "name": "AutoDeconstruct",
      "enabled": "true"
    },
    {
      "name": "AutoTrash",
      "enabled": "true"
    },
    {
      "name": "BlueprintExtensions",
      "enabled": "true"
    },
    {
      "name": "Bottleneck",
      "enabled": "true"
    },
    {
      "name": "clock",
      "enabled": "true"
    },
    {
      "name": "DiscoScience",
      "enabled": "true"
    },
    {
      "name": "DyWorld",
      "enabled": "true"
    },
    {
      "name": "even-distribution",
      "enabled": "true"
    },
    {
      "name": "EvoGUI",
      "enabled": "true"
    },
    {
      "name": "ExpandedInventory",
      "enabled": "true"
    },
    {
      "name": "Fill4Me",
      "enabled": "true"
    },
    {
      "name": "Flow Control",
      "enabled": "true"
    },
    {
      "name": "FNEI",
      "enabled": "true"
    },
    {
      "name": "helmod",
      "enabled": "true"
    },
    {
      "name": "MaxRateCalculator",
      "enabled": "true"
    },
    {
      "name": "Nanobots",
      "enabled": "true"
    },
    {
      "name": "nixie-tubes",
      "enabled": "true"
    },
    {
      "name": "OpteraLib",
      "enabled": "true"
    },
    {
      "name": "ore-eraser",
      "enabled": "true"
    },
    {
      "name": "PickerAtheneum",
      "enabled": "true"
    },
    {
      "name": "PickerBeltTools",
      "enabled": "true"
    },
    {
      "name": "PickerDollies",
      "enabled": "true"
    },
    {
      "name": "PickerExtended",
      "enabled": "true"
    },
    {
      "name": "research-progress",
      "enabled": "true"
    },
    {
      "name": "Squeak Through",
      "enabled": "true"
    },
    {
      "name": "stdlib",
      "enabled": "true"
    },
    {
      "name": "TinyStart",
      "enabled": "true"
    },
    {
      "name": "tree_collision",
      "enabled": "true"
    },
    {
      "name": "VehicleSnap",
      "enabled": "true"
    },
    {
      "name": "WagonColors",
      "enabled": "true"
    },
    {
      "name": "Waterfill_v17",
      "enabled": "true"
    },
    {
      "name": "WaterWell",
      "enabled": "true"
    },
    {
      "name": "what-is-it-really-used-for",
      "enabled": "true"
    },
    {
      "name": "YARM",
      "enabled": "true"
    }
  ]
}

**Comment by Dysoch** [comment]
I had some errors when i ported it to 0.17, so i removed it for now. The Deadlock loaders will come back though, cant say when

**Comment by DaveSharman** [comment]
Ok, sounds good.     Man this mod is a logistics nightmare.  Makes the game much more interesting than vanilla again and again.
