### ISSUE TITLE
Spitter damage

### ISSUE THREAD

**Issue by Darkfizzz** [Dysoch/DyWorld#314]
Spitters seem to deal 38,000 damage now after updating to 0.9.2

**Comment by Dysoch** [comment]
fixed

**Comment by Dysoch** [comment]
did you enabled enemies while still having normal enemies in the world?

**Comment by Darkfizzz** [comment]
No I had only just started the pack, with only this mod affecting enemies.  After just updating they got that huge.  Thank you for fixing it so quick :D
