### ISSUE TITLE
Mod settings not multi-player safe

### ISSUE THREAD

**Issue by billbo99** [Dysoch/DyWorld#315]
Trying to log into a MP server,  keep getting this error
![](https://cdn.discordapp.com/attachments/390845336400429057/639751918687748116/unknown.png)

Base on what has been stated by "Rseding" on of the Factorio Devs you should not be using IF statements around a REQUIRE method

EG  data-update.lua
```  
if settings.startup["DyWorld_Extraction"].value then
	require("data.extraction.data")
end
```

https://forums.factorio.com/viewtopic.php?f=23&t=46364&p=267014&hilit=require+mismatch#p267014

**Comment by Dysoch** [comment]
will rewrite it to make sure it wont happen
