### ISSUE TITLE
Loaders seem to have broken.

### ISSUE THREAD

**Issue by RoryBecker** [Dysoch/DyWorld#323]
Just upgraded from 0.93 -> 0.94 (whilst also upgrading factorio from 0.17 -> 0.18.*)

All my loaders are definitly broken. They appear to refuse to connect to belts passing goods through 90 degrees.
I'll admit I'm not sure if this issue is based in Dyworld or Factorio 0.18, but figured I'd start by reporting it here.

**Comment by ppvolto** [comment]
Currently ONLY the output in the LEFT is Working on NEW placed Loaders but input i currently didn't find a problem...

**Comment by RoryBecker** [comment]
Excellent work. Seems Perfect. Many Thanks
