### ISSUE TITLE
Missing recepies in Blast furnance MK1

### ISSUE THREAD

**Issue by bagalas** [Dysoch/DyWorld#325]
Hi,

I'm wathcing KoS youtube Dyworld series and she can make molten lead and steel in Blast Furnance Mk1. 
I cant. The recepies are missing. While I can make them in heated furnances the Bronze is missing as well. This prevents creating blue scince and advance in the game. (Blast furnance MK2 needs Elektrum plate which is locked behid Blue)
Maybe its local. A feedback would nice if its only my game or not. Thanks.

Game version. 0.18.3
Mod version: 0.9.5
Other mods: the usual QoL mods plus Nanobots, Turret shields. RSO, Optera's Lib, Factorio standard Libary

**Comment by XxN4BxX** [comment]
if you didnt know, the first research of the blast furnace only unlocks the MK1 metallurgy buildings, you need the next research to unlock the recipes

**Comment by Dysoch** [comment]
the blast furnaces are still a bit buggy. should be fixed for next version. 
And true, the first metallurgy recipe unlocks the machine, second tech unlocks the recipes

**Comment by bagalas** [comment]
> if you didnt know, the first research of the blast furnace only unlocks the MK1 metallurgy buildings, you need the next research to unlock the recipes

I have all the tech required. RoryBecker reported the issue just after me as well. I only happen to suspect that the MK1 furnance should have the ability to melt bronze, lead and others beacuse I watched KoS dyworld series in wich she could do them prior to 0.18.

Thank you Dysoch for replying. The modpack is awesome. Cant wait to continue playing it.

**Comment by Dysoch** [comment]
fix should be uploaded in 1 or 2 days (gonna balance a few more quickly, and little time sadly)
