### ISSUE TITLE
Cyclical loop of requirements

### ISSUE THREAD

**Issue by RoryBecker** [Dysoch/DyWorld#326]
Game version. 0.18.3
Mod version: 0.9.5

It seems that this version of Dyworks requires an impossible loop.

Molten Electrum can only be constructed in an MK2 blast furnace or above.
Mk2 BF requires advanced circuits which require Electrum plating.

**Comment by Dysoch** [comment]
will be fixed for next version

**Comment by RoryBecker** [comment]
You are "The Man" (Or possibly "The Woman" :) 
Thank you very much for all your work on this project. Very enjoyable.
