### ISSUE TITLE
Furnace Mk 3 temperatures - how to heat

### ISSUE THREAD

**Issue by GregDomjan** [Dysoch/DyWorld#336]
To get to stainless steel we need Furnace Mk 3,  but on trying to use it with a temperature of 970 getting no output.  Then noticed may need temp of 1500?  

Besides Nuclear not finding how to achieve this temperature, did I miss something or is the next step really nuclear?

**Comment by Dytand** [comment]
If you ask me, then i will say nuclear.

**Comment by MarcusNewman** [comment]
Yep nuclear is the way to go. I was a little surprised my first run, but it's not too hard even without kovorex.
