### ISSUE TITLE
0.97 Many weapons are damaging untargetted structures

### ISSUE THREAD

**Issue by GregDomjan** [Dysoch/DyWorld#340]
Is it intended?

Lasers seemed good having long distance,  however they blow the walls away trying to attack what is on the other side,  or blow each other away when the natives get amongst a defensive line.

Personal Chaingun also damages walls when shooting at the natives on the other side.

Sniper gun doesn't seem to have this 'problem'

**Comment by Dysoch** [comment]
You probably have Combat Overhaul setting active, which means all guns shoot projectiles which hit the very first thing they come into contact with. This is an intended feature of that setting.

If not the case, please reopen this issue
