### ISSUE TITLE
0.97 Advanced Oil process balancing? 

### ISSUE THREAD

**Issue by GregDomjan** [Dysoch/DyWorld#341]
Maybe I'm just unaware of a step, but at the moment I can't see a way to use advanced oil as the kero to solid fuel ratio seems off - the only thing I have to use kero is rocket fuel, or to dump it?

For 1000 crude oil,  you get 450 kero and 250 heavy oil,  converting all heavy to light gives 187.5 light, and all light to solid fuel gives 18.7.     
Finally for rocket fuel the only known outlet for kero ,  the 450 kero can make 9 rocket fuel, it also takes 90 solid fuel - but only have 18.7 from earlier processing.
Even if All the 550 Petroleum is also converted to solid fuel that only gets to 46.25 only half the required.

**Comment by MarcusNewman** [comment]
I ended up just burning all my extra kerosine, but I'd love to hear some other solutions as well.
