### ISSUE TITLE
Game crash 0.18.14 

### ISSUE THREAD

**Issue by X3r0n3** [Dysoch/DyWorld#345]
![Capture](https://user-images.githubusercontent.com/62379835/77056250-75492d00-69d2-11ea-92f7-17c7de1bfb3b.PNG)

**Comment by TheBoardMan** [comment]
Same here. Just after becoming level 30.

**Comment by olinator990** [comment]
Check discord there is a solution :)

**Comment by simpsus** [comment]
In the discord channel "bug-reports" there is a "quick and dirty fix" for the game postet on 03/19/2020
It involves downloading two files and overriding them in the (to be unzipped) mod zip. The updated files comment the lines causing th crash
