### ISSUE TITLE
Discord link not working

### ISSUE THREAD

**Issue by donoya** [Dysoch/DyWorld#385]
I tried joining the Discord to see if there was a public version of Dy-World Dynamics that works with the files uploaded to the mod portal, but it looks like the Discord link is not working. I remember I really liked the depth that existed in the old Dy-Tech project, so seeing this project is awesome, by the way.

**Comment by Dysoch** [comment]
This happened due to channel changes in discord (the original link goes to a channel no longer active).
I have updated all links to a new one

https://discord.gg/yHJaZrq5Ww

DyWorld-Dynamics will be available soon, more info found in announcement channel on my discord
