### ISSUE TITLE
unable to build solarpanels

### ISSUE THREAD

**Issue by JanEggers** [Dysoch/DyWorld#485]
**Describe the bug**
I unlocked electric tec 4 but am still not able to build solar panels or accumulators

**Screenshots**
![image](https://user-images.githubusercontent.com/6747376/139596282-369b2252-2cef-45e2-b812-c5e5b915bc9e.png)

![image](https://user-images.githubusercontent.com/6747376/139596310-f397ed4c-7369-4157-b291-37f1066eaa7a.png)

**Comment by JanEggers** [comment]
fnei shows the vanilla solar tec as requirement for them. but that does not exit with your mod

![image](https://user-images.githubusercontent.com/6747376/139596842-29172ba6-29b6-4742-829b-b3161197c9d3.png)

**Comment by sirwelshyy** [comment]
i have the same problem

**Comment by Dysoch** [comment]
Fixed for next build
