### ISSUE TITLE
a few problems i've come across so far

### ISSUE THREAD

**Issue by sirwelshyy** [Dysoch/DyWorld#489]
navigation satellite 
needs plastic bar to make, cant find no plastic bar recipes

shotgun
can make shotguns but no recipes for shotgun ammo

transport belts3, undergrounds, splitters, loaders all use same resources as transport belts1, is this a mistake?

can't install solar panels in armours, when trying to install, square turns red.

can't research heatshield 
have learnt all research that leads up to it

**Comment by Dysoch** [comment]
shotgun and transport belt 3 and above will be changed in future updates, the rest is fixed
