### ISSUE TITLE
Can't Craft Automation Science Packs

### ISSUE THREAD

**Issue by AndrewBezold** [Dysoch/DyWorld#546]
**Describe the bug**
There appears to be an issue with the recipe for Automation Science Packs (I assume it's a mod load order issue, but I don't know that for certain).  The item can only be constructed in assemblers that don't exist - Space Assembling Machine, Space Manufactory, Assembling Machine 2, and Assembling Machine 3, rather than Basic Assembler, Advanced Assembler, Nano Assembler, and Quantum Assembler.  Though the Basic Assembler and Assembling Machine 2 look identical, they are not the same building.  It's forced me to stop playing, as there is no way to progress past this point.

**Screenshots**
![20220502210515_1](https://user-images.githubusercontent.com/5451903/166390948-9c71be7f-c3f2-4ecf-b419-a2a31698bae1.jpg)

**Information (please complete the following information):**
 - Version 0.2.2
 - Mods used
   - AAI Containers and Warehouses 0.2.10
   - AAI Industry 0.5.17
   - AAI Signal Transmission 0.4.4
   - Advanced Fluid Handling 1.1.2
   - Alien Biomes 0.6.7
   - Base Mod 1.1.57
   - DyComPa 0.1.7
   - DyCore 0.1.4
   - DyWorld-Dynamics 0.2.2
   - Even Distribution 1.0.10
   - Factorio Library 0.10.1
   - Factorio Standard Library 1.4.6
   - Helmod 0.12.9
   - InformaTron 0.2.2
   - Jetpack 0.3.2
   - LTN 1.16.7
   - LTN Combinator Modernized 1.0.10
   - LTN Manager 0.4.12
   - Nanobots 3.2.19
   - Robot Attrition 0.5.12
   - Shield Projector 0.1.3
   - Space Exploration 0.5.114
   - Space Exploration Graphics 1 0.5.15
   - Space Exploration Graphics 2 0.1.2
   - Space Exploration Graphics 3 0.1.1
   - Space Exploration Graphics 4 0.1.1
   - Space Exploration Graphics 5 0.1.2
   - Space Exploration HR Graphics 0.5.1
   - Space Exploration Postprocess 0.5.30

**Additional context**

**Comment by Dysoch** [comment]
Has been fixed in a previous commit
