### ISSUE TITLE
Bug Error at loading in DyCore (french version)

### ISSUE THREAD

**Issue by omega2003** [Dysoch/DyWorld#549]
**Describe the bug**
When loading wiith game in French I got error : Duplicate key "refined-concrete".
The line "refined-concrete=Béton raffiné" is present twice in the file "DyCore\locale\fr\looped.cfg".

If I delete the second copy of this line the error disappears.

**Screenshots**
![Error DyCore](https://user-images.githubusercontent.com/3497847/191872812-daf711bd-d45c-4cdf-9c65-0aca1796176a.PNG)

**Information (please complete the following information):**
 - Version 0.1.4

**Comment by MaxiderZocker** [comment]
Hey, this has already been fixed in the github branch. there just hasn't been a new version since
