### ISSUE TITLE
Mod no longer works, causes spaceexploration to crash during load

### ISSUE THREAD

**Issue by McFrugal** [Dysoch/DyWorld#550]
**Describe the bug**
Trying to launch factorio with only the required mods for DyWorld-Dynamics causes a crash, specifically space exploration crashing.

**Information (please complete the following information):**
 - Version [e.g. 0.8.0]
1.1.76
 - Mods used
DynWorld-Dynamics, and all its dependencies.

**Comment by LetterN** [comment]
This is caused by `lab-1` requiring some metals (like `steel-plate`.) Space exploration for some reason re-sorts all lab item input using `data.raw.tool` which `steel-plate` doesn't exist in

**Comment by MaxiderZocker** [comment]
The simplest fix is to just use the correct space exploration version as stated by dyworld.

**Comment by MaxiderZocker** [comment]
and it is a known bug, but dysoch doesn't have a lot of time to fix things.

**Comment by LetterN** [comment]
I've used latest space-exploration and it works with the workarounds

**Comment by jurrejelle** [comment]
Atleast for now, would it be possible to set the required SE version to be =0.5.92 instead of >=? Can make a PR for this if needed

**Comment by jurrejelle** [comment]
Sidenote, but it still works with the suggested workarounds as far as I can tell.

For anyone else trying to manually patch it, for the second workaround suggested by @LetterN, you need to edit "technology.lua" in the phase3 folder :)
