### ISSUE TITLE
Copper axe vs. iron or steel axe seems oddly balanced

### ISSUE THREAD

**Issue by Alexis-Grimm** [Dysoch/DyWorld#9]
Is it intended for the copper axe to have a higher mining power than both the steel axe and iron axe rendering both slower than copper? because whenever i mine i have my copper axes which have a mining power of 5 as opposed to my iron and steel ones which have 3 and 4 respectively, i mean sure the copper axes have reduced durability (3500 as opposed to 5000) but keeping a stack of 20 on me is sufficient.

Using factorio version 0.15.2 and of course dyworld 0.1.0

**Comment by Dysoch** [comment]
it is an intended feature. In real life copper is lighter then iron, so you can swing it harder, while iron is stronger
